name: Build and Deploy to EKS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-south-1
  ECR_BACKEND: portfolio-backend
  ECR_FRONTEND: portfolio-frontend
  CLUSTER_NAME: portfolio-eks

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::547619294448:role/github-actions-eks-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin \
        547619294448.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build Backend Image
      run: |
        docker build -t backend ./backend
        docker tag backend:latest \
        547619294448.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_BACKEND:latest
        docker push \
        547619294448.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_BACKEND:latest

    - name: Build Frontend Image
      run: |
        docker build -t frontend ./frontend
        docker tag frontend:latest \
        547619294448.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_FRONTEND:latest
        docker push \
        547619294448.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_FRONTEND:latest

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --name $CLUSTER_NAME \
          --region $AWS_REGION

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
        kubectl rollout restart deployment backend
        kubectl rollout restart deployment frontend
